name: uic_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  just_audio: ^0.9.36
  open_file: ^3.3.2
  path_provider: ^2.1.2
  json_annotation: ^4.8.1
  get_it: ^7.6.7
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  audio_video_progress_bar: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
